### PR TITLE
Number of events and users is the same

### PR DESCRIPTION
**Pull request by ari7946**

### CODE REVIEW

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-10)

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-10)

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-10)

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-10)

**Comment by ari7946** [comment]
This branch still needs to be covered by a cypress test

**Pull request merged**
