### PR TITLE
Add loading screen to project list

### PR DESCRIPTION
**Pull request by ari7946**

### CODE REVIEW

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-11)

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-11)

**Comment by ari7946** [comment]
This branch is still open because it needs a cypress test

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-11)

**Review by mentor-tara — APPROVED** [review]
Go go go :smile:[](prolog-11)

**Pull request merged**
